# -*- coding: utf-8 -*-
"""iris_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBfx-oEyhXIsUN_ZJZwLcj3ayzgQIfOe
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Load Dataset
df = pd.read_csv("Iris.csv")

# Display data
print(df.head())

# Dataset Information
print(df.shape)
print(df.info())
print(df.describe())

# Missing Values
print(df.isnull().sum())

# Species Count
print(df["Species"].value_counts())

# Histogram
df.hist(figsize=(10,8))
plt.show()

# Pairplot
sns.pairplot(df, hue="Species")
plt.show()

# Correlation Heatmap
numeric_df = df.drop(columns=["Species"])

plt.figure(figsize=(8,6))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.show()

# Features and Target
X = df.drop(columns=["Species"])
y = df["Species"]

# Split Data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Model
model = KNeighborsClassifier(n_neighbors=3)

model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:",
      accuracy_score(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.show()

# Classification Report
print(
    classification_report(
        y_test,
        y_pred
    )
)

# New Prediction
sample = [[1,5.1,3.5,1.4,0.2]]

prediction = model.predict(sample)

print("Predicted Species:",
      prediction[0])